# Site configuration
domain: "https://b-liu14.github.io"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://b-liu14.github.io" # the base hostname & protocol for your site
permalink: /:title/
avatar: /static/avatar.JPG
about: /static/about.JPG
favicon: http://7xof48.com1.z0.glb.clouddn.com/favicon.png
CV-en: "/media/CV-Bin Liu-Tsinghua University-17888825884.pdf"
CV-zh: "/media/中文简历-刘斌-清华大学软件学院-17888825884.pdf"

basecss:
# Theme specific configuration
title: kevin

# Contact and social media links
twitter_username: songrogero
github_username: b-liu14
facebook_username: song.roger.1
instagram_username: songroger198
linkedin_username: songroger

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'scripts']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
