# Site configuration
domain: "https://b-liu14.github.io"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://b-liu14.github.io" # the base hostname & protocol for your site
permalink: /:title/
avatar: /static/image/avatar.JPG
about: /static/image/about.JPG
favicon: /static/image/favicon.jpeg
CV-en: "/media/CV-Bin Liu-Tsinghua University-17888825884.pdf"
CV-zh: "/media/中文简历-刘斌-清华大学软件学院-17888825884.pdf"

basecss:
# Theme specific configuration
title: kevin's blog

# Contact and social media links
# twitter_username: songrogero
github_username: b-liu14
# facebook_username: song.roger.1
# instagram_username: songroger198
# linkedin_username: songroger

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'scripts']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: true

gems: ['jekyll-paginate', 'jekyll-archives']
jekyll-archives:
    enabled:
      - year
      - month
      - tags
    layouts:
      year: year-archive
      month: month-archive
      tag: tag-archive
    permalinks:
      year: '/archives/year/:year/'
      month: '/archives/month/:year-:month/'
      tag: '/archives/tag/:name/'
# Pagination
paginate: 5
paginate_path: /archives/page:num

excerpt_separator: "\n\n\n"

# Tag related settings.
tag_page_dir: archives/tag

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: post
      categories: technology_blog
      location: Beijing China
      description: 无描述
